[pytest]
testpaths = tests
pythonpath = .
addopts = --strict-markers --html=reports/report.html --self-contained-html
markers =
    valid: happy-path tests with valid input data
    invalid: tests with invalid or inopportune input data

