[pytest]
testpaths = tests
addopts = --strict-markers --html=reports/relatorio.html --self-contained-html
markers =
    valido: Testes com massa de dados valida
    invalido: Testes com massa de dados invalida
